package com.sample.rules
 
import creatures.*;
import mechanics.*;
 
rule "Roll for initiative"
	salience 9001
	when
        turn : Turn(status == Turn.State.INIT)
        c : Creature()
    then
    	c.setStatPerm("initiative",Utils.roll("1d20", c.getAdvantage("initiative"))+c.getBonus("initiative"));
        System.out.println( "Initiative: " + c.getName() );
        
        
end

rule "FIGHT START"
salience 9000
	when
		turn : Turn(status == Turn.State.INIT)
	then
		System.out.println("Gabibbo");
		turn.setStatus(Turn.State.FIGHT);
		update(turn);
end

rule "START OF TURN"
	salience 8800
	when
		turn : Turn(status == Turn.State.FIGHT)
		act : Action()
		c : Creature(name == act.originCreature.name)
	then
	//TODO start of turn effects
	System.out.println(c.getName()+": Start of turn");
end

rule "ATTACK"
salience 8700
	activation-group "ACTION"
	when
		turn : Turn(status == Turn.State.FIGHT)
		act : Action(type == Action.Type.ATTACK)
		c : Creature(name == act.originCreature.name)
		
	then
		//TODO attack
		System.out.println(c.getName()+": Attack");
		c.setFought(true);
end

rule "CAST"
salience 8700
	activation-group "ACTION"
	when
		turn : Turn(status == Turn.State.FIGHT)
		act : Action(type == Action.Type.CAST)
		c : Creature(name == act.originCreature.name)
		
	then
		//TODO cast
		System.out.println(c.getName()+": Cast");
		c.setFought(true);
end

rule "DODGE"
salience 8700
	activation-group "ACTION"
	when
		turn : Turn(status == Turn.State.FIGHT)
		act : Action(type == Action.Type.DODGE)
		c : Creature(name == act.originCreature.name)
		
	then
		
		System.out.println(c.getName()+": Cast");
		c.setFought(true);
end

rule "HELP"
salience 8700
	activation-group "ACTION"
	when
		turn : Turn(status == Turn.State.FIGHT)
		act : Action(type == Action.Type.HELP)
		c : Creature(name == act.originCreature.name)
		
	then
		//TODO help
		System.out.println(c.getName()+": Cast");
		c.setFought(true);
end

rule "HIDE"
salience 8700
	activation-group "ACTION"
	when
		turn : Turn(status == Turn.State.FIGHT)
		act : Action(type == Action.Type.HIDE)
		c : Creature(name == act.originCreature.name)
		
	then
		//TODO hide
		System.out.println(c.getName()+": Cast");
		c.setFought(true);
end

query "getCreatures"
	$result: Creature()
end



